version: '3.7'

services:
  tomcat:
    image: qtc/tomcat-jmxmp
    build: .
    environment:
      - CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9011 -Djava.rmi.server.hostname=iinsecure.dev -Dcom.sun.management.jmxremote.ssl=true -Djavax.net.ssl.keyStore=/opt/store.p12 -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.keyStoreType=pkcs12 -Dcom.sun.management.jmxremote.registry.ssl=true
    volumes: 
      - ./resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./resources/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./resources/conf/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./resources/trust/store.p12:/opt/store.p12
    networks:
      tomcat_net:
        ipv4_address: 172.30.0.2
    init: true

networks:
  tomcat_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
