version: '3.7'

services:
  tomcat:
    image: qtc/tomcat-jmxmp
    build: .
    environment:
      - > 
        CATALINA_OPTS=
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9011
        -Djava.rmi.server.hostname=iinsecure.dev
        -Djavax.net.ssl.keyStorePassword=password
        -Djavax.net.ssl.keyStore=/opt/store.p12
        -Djavax.net.ssl.keyStoreType=pkcs12
        -Dcom.sun.management.jmxremote.ssl=true
        -Dcom.sun.management.jmxremote.registry.ssl=true
      - >
        DELETE_THIS_AND_THE_ABOVE_LINE_TO_ENABLE_PASSWORD_AUTH=
        -Dcom.sun.management.jmxremote.authenticate=true
        -Dcom.sun.management.jmxremote.password.file=/opt/jmxremote.password
        -Dcom.sun.management.jmxremote.access.file=/opt/jmxremote.access
    volumes: 
      - ./resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./resources/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./resources/conf/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./resources/commons-collections-3.1.jar:/usr/lib/jvm/default-jvm/jre/lib/ext/commons-collections-3.1.jar
      - ./resources/trust/store.p12:/opt/store.p12
      - ./resources/conf/jmxremote.password:/opt/jmxremote.password
      - ./resources/conf/jmxremote.access:/opt/jmxremote.access
      - ./resources/conf/jmxmp.access:/opt/jmxmp.access
    networks:
      tomcat_net:
        ipv4_address: 172.30.0.2
    init: true

networks:
  tomcat_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
