version: '3.7'

services:

    tomcat:

      image: docker.pkg.github.com/qtc-de/beanshooter/tomcat8-jmxmp:1.0
      environment:
        - > 
          CATALINA_OPTS=
          -Dcom.sun.management.jmxremote
          -Dcom.sun.management.jmxremote.local.only=false
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.port=9010
          -Dcom.sun.management.jmxremote.rmi.port=9011
          -Djava.rmi.server.hostname=iinsecure.dev
          -Djavax.net.ssl.keyStorePassword=password
          -Djavax.net.ssl.keyStore=/opt/store.p12
          -Djavax.net.ssl.keyStoreType=pkcs12
          -Dcom.sun.management.jmxremote.ssl=true
          -Dcom.sun.management.jmxremote.registry.ssl=true
        - >
          DELETE_THIS_AND_THE_ABOVE_LINE_TO_ENABLE_PASSWORD_AUTH=
          -Dcom.sun.management.jmxremote.authenticate=true
          -Dcom.sun.management.jmxremote.password.file=/opt/jmxremote.password
          -Dcom.sun.management.jmxremote.access.file=/opt/jmxremote.access
      init: true
      #volumes: 
      #  - ./resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
      #  - ./resources/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      #  - ./resources/conf/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      #  - ./resources/trust/store.p12:/opt/store.p12
      #  - ./resources/conf/jmxremote.password:/opt/jmxremote.password
      #  - ./resources/conf/jmxremote.access:/opt/jmxremote.access
      #  - ./resources/conf/jmxmp.access:/opt/jmxmp.access
